### ISSUE TITLE
Mount attempt gives json error

### ISSUE THREAD

**Issue by julesfm** [robin-thomas/GDFS#1]
I'm trying to get it working on Ubuntu 15.10.
I've built it okay, that seems fine.
But when I try to do
/usr/local/bin/mount.gdfs -m /mnt/gdrive -df --log_path /opt/gdfs --log_level DEBUG -o debug,allow_root,direct_io
I just get this error:
[ERROR] [] => Value error doesnt exist in json output
Running gauth appears to have worked okay, it said it had successfully got an access token.

Where is it likely to be going wrong?

Here is the gdfs.log output:

> ###### 
> # 
> # GOOGLE DRIVE FILE SYSTEM
> # 
> # v1.0.0
> # Robin Thomas
> # robinthomas2591@gmail.com
> # 
> ###### 

18-04-2016 16:36:02,   DEBUG Thread 42816,          mount.cc:76 => <-- Entering set_mount_opt() -->
18-04-2016 16:36:02,   DEBUG Thread 42816,          mount.cc:80 => <-- Exiting set_mount_opt() -->
18-04-2016 16:36:02,   DEBUG Thread 42816,         mount.cc:134 => <-- Entering mount_fs() -->
18-04-2016 16:36:02,   DEBUG Thread 42816,          mount.cc:95 => <-- Entering is_fs_running() -->
18-04-2016 16:36:02,   DEBUG Thread 42816,         mount.cc:114 => GDFS is not running.
18-04-2016 16:36:02,   DEBUG Thread 42816,         mount.cc:117 => <-- Exiting is_fs_running() -->
18-04-2016 16:36:02,   DEBUG Thread 42816,         gdfs.cc:1487 => <-- Entering initGDFS() -->
18-04-2016 16:36:02,   DEBUG Thread 42816,           auth.cc:58 => <-- Entering load_auth_file() -->
18-04-2016 16:36:02,   DEBUG Thread 42816,           auth.cc:87 => <-- Exiting load_auth_file() -->
18-04-2016 16:36:02,   DEBUG Thread 42816,         gdapi.cc:399 => <-- Entering get_root() -->
18-04-2016 16:36:03,   DEBUG Thread 42816,         mount.cc:174 => <-- Entering unmount_fs() -->
18-04-2016 16:36:03,   DEBUG Thread 42816,          mount.cc:95 => <-- Entering is_fs_running() -->
18-04-2016 16:36:03,   DEBUG Thread 42816,         mount.cc:114 => GDFS is not running.
18-04-2016 16:36:03,   DEBUG Thread 42816,         mount.cc:117 => <-- Exiting is_fs_running() -->
18-04-2016 16:36:03, WARNING Thread 42816,         mount.cc:193 => Trying to unmount fs at /mnt/gdrive. Not mounted.
18-04-2016 16:36:03,   DEBUG Thread 42816,         mount.cc:199 => <-- Exiting unmount_fs() -->

And one other question: when I run mount.gdfs should the mount point directory /mnt/gdrive exist or not? With other filesystems, the mount point should always exist beforehand. But from your example using /tmp/robin I'm unsure.

Thanks!
Jules.

**Comment by robin-thomas** [comment]
Hi Jules,

I have send an email to you earlier.
Check it out.
Let me know if the error persists.

**Comment by robin-thomas** [comment]
Solved. Closing the issue.
